name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app.py'
      - 'templates/**'
      - 'requirements.txt'
      - 'models/**'
      - 'data/**'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/deploy-cloudrun.yaml'

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build and push container image
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ secrets.GCP_REGION }}
          REPO: ${{ secrets.GAR_REPO }}
        run: |
          IMAGE_URI=${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/devops-ia-2:${GITHUB_SHA}
          docker build -t ${IMAGE_URI} .
          docker push ${IMAGE_URI}
          echo "IMAGE_URI=${IMAGE_URI}" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        env:
          SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}
          REGION: ${{ secrets.GCP_REGION }}
        run: |
          gcloud run deploy ${SERVICE} \
            --image ${IMAGE_URI} \
            --region ${REGION} \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --cpu 2 \
            --memory 4Gi \
            --timeout 900

      - name: Show Cloud Run URL
        run: gcloud run services describe ${{ secrets.CLOUD_RUN_SERVICE }} --region ${{ secrets.GCP_REGION }} --format 'value(status.url)'
